### PR TITLE
Otherwise git hook fails if only untracked

### PR DESCRIPTION
**Pull request by mhmxs**
files are in the repo. Newer Gosec doesn't like net/http package, so to pass gosec i had to change them.

### CODE REVIEW

**Comment by Mojachieee** [comment]
What was the gosec issue we were hitting? It seems odd that the Go standard library would fail

**Comment by mhmxs** [comment]
@Mojachieee standard library `ListanAndServe` has the default infinite timeout :(

**Comment by Mojachieee** [comment]
> @Mojachieee standard library `ListanAndServe` has the default infinite timeout :(

It seems a bit overkill to switch to a gin server, can't we set the timeouts?
```
srv := &http.Server{
    ReadTimeout: 5 * time.Second,
    WriteTimeout: 10 * time.Second,
}
srv.ListenAndServe()
```

**Comment by mhmxs** [comment]
@Mojachieee please take a look :)

**Review by Mojachieee — APPROVED** [review]

**Pull request merged**
